name: Terraform Destroy

on:
  workflow_run:
    workflows:
      - Terraform Deployment
      - Run Prowler Scan
    types:
      - completed
  workflow_dispatch:

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
      
jobs:
  destroy:
    if: ${{ github.event.workflow_run.conclusion == 'failure' || github.event_name == 'workflow_dispatch' }}  # 실패 또는 수동 실행 시 실행
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      # AWS 자격 증명 구성
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ap-northeast-2

      # Terraform Init
      - name: Terraform Init
        run: terraform init

      # Terraform Destroy
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
