name: Terraform Destroy

on:
  workflow_run:
    workflows:  # 실패 시 이 워크플로우를 트리거할 워크플로우 이름을 명시
      - Deploy Infrastructure  # 배포 워크플로우 이름을 작성
      - Run Prowler Security Scan  # 다른 워크플로우 이름도 추가 가능
    types:
      - completed  # 완료 시(성공 또는 실패)
      
jobs:
  destroy:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}  # 실패한 경우에만 실행
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      # AWS 자격 증명 구성
      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set aws_session_token $AWS_SESSION_TOKEN
          aws configure set region ap-northeast-2

      # Terraform Init
      - name: Terraform Init
        run: terraform init

      # Terraform Destroy
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        