name: Terraform Destroy

on:
  workflow_dispatch:  # 수동으로 워크플로우 실행

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      # AWS 자격 증명 구성
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        with:
            aws-access-key-id: $AWS_ACCESS_KEY_ID
            aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
            aws-session-token: $AWS_SESSION_TOKEN
            aws-region: ap-northeast-2

      # Terraform Init
      - name: Terraform Init
        run: terraform init

      # Terraform Destroy
      - name: Terraform Destroy
        run: terraform destroy -auto-approve