name: Generate Inframap

on:
  push:
    branches:
      - main

jobs:
  inframap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Inframap
        run: |
          curl -fsSL https://raw.githubusercontent.com/cycloidio/inframap/master/scripts/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          
          - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: 1.9.8
  
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ap-northeast-2
            
      - name: Terraform Init
        run: terraform init

      - name: Generate Terraform Plan
        run: terraform plan -out=tfplan.binary

      - name: Generate Inframap from Terraform Plan
        run: |
          terraform show -json tfplan.binary | inframap generate --tfstate > inframap-output.dot
          dot -Tpng inframap-output.dot -o inframap-diagram.png

      - name: Upload Inframap Diagram
        uses: actions/upload-artifact@v4
        with:
          name: inframap-diagram
          path: inframap-diagram.png