name: Infracost Workflow

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  infracost-pull-request-checks:
    name: Infracost Pull Request Checks
    if: github.event_name == 'infracost-report' && (github.event.action == 'opened' || github.event.action == 'synchronize')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # Required to post comments

    steps:
      # Infracost CLI 설치
      - name: Setup Infracost
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: '${{ github.event.pull_request.base.ref }}'
      
      
      # 비용 분석 수행
      - name: Run Infracost
        run: |
          infracost breakdown --path=. \
                              --format=json \
                              --out-file=infracost-report.json

      - name: Checkout PR branch
        uses: actions/checkout@v4

        # Generate an Infracost diff and save it to a JSON file.
      - name: Generate Infracost diff
        run: |
          infracost diff --path=. \
                         --format=json \
                         --compare-to=/tmp/infracost-base.json \
                         --out-file=/tmp/infracost.json

      # PR에 비용 분석 결과 주석 추가
      - name: Post Infracost Comment
        if: github.event_name == 'pull_request'
        run: |
          infracost comment github --path=infracost-report.json \
                                   --repo=$GITHUB_REPOSITORY \
                                   --github-token=${{ github.token }} \
                                   --pull-request=${{ github.event.pull_request.number }} \
                                   --behavior=update

      # main 브랜치에 푸시된 결과를 Infracost Cloud에 업로드
      - name: Upload Infracost Report to Cloud
        if: github.event_name == 'push'
        run: |
          infracost upload --path=infracost-report.json || echo "Upload to Infracost Cloud failed, continuing workflow"