name: Generate Inframap

on:
  push:
    branches:
      - main

jobs:
  inframap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.22'
      - run: go version

      - name: Clone Inframap Repository
        run: git clone https://github.com/cycloidio/inframap

      - name: Build Inframap
        run: |
          cd inframap
          go mod download
          make build
          sudo mv bin/inframap /usr/local/bin/

      - name: Verify Inframap Installation
        run: inframap version
  
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ap-northeast-2

      - name: Download TFState from S3
        run: |
          aws s3 cp s3://terraform-state-bucket-cs-0001/s3-backend/terraform.tfstate ./terraform.tfstate

      - name: Generate Inframap from tfstate
        run: |
          inframap generate --tfstate=terraform.tfstate > inframap-output.dot
          dot -Tpng inframap-output.dot -o inframap-diagram.png

      - name: Upload Inframap Diagram
        uses: actions/upload-artifact@v4
        with:
          name: inframap-diagram
          path: inframap-diagram.png