name: Generate Inframap

on:
  push:
    branches:
      - main

jobs:
  inframap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Terraform
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          curl -fsSL https://releases.hashicorp.com/terraform/$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r .current_version)/terraform_$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r .current_version)_linux_amd64.zip -o terraform.zip
          unzip terraform.zip
          sudo mv terraform /usr/local/bin/

      - name: Install Inframap
        run: |
          curl -fsSL https://raw.githubusercontent.com/cycloidio/inframap/master/scripts/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          
      - name: Initialize Terraform
        run: terraform init

      - name: Generate Terraform Plan
        run: terraform plan -out=tfplan.binary

      - name: Generate Inframap from Terraform Plan
        run: |
          terraform show -json tfplan.binary | inframap generate --tfstate > inframap-output.dot
          dot -Tpng inframap-output.dot -o inframap-diagram.png

      - name: Upload Inframap Diagram
        uses: actions/upload-artifact@v4
        with:
          name: inframap-diagram
          path: inframap-diagram.png