name: Run Prowler Scan

on:
  workflow_run:
    workflows: ["Terraform Deployment"]
    types:
      - completed

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  prowler-scan:
    runs-on: ubuntu-latest
    name: Run Prowler Scan
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ap-northeast-2

      - name: Install and Run Prowler on Specific Resources
        run: |
          sudo apt update
          sudo apt install -y pipx
          pipx install prowler
          prowler -v

          # 현재 날짜와 시간을 파일 이름에 추가
          TIMESTAMP=$(date '+%Y-%m-%d_%H-%M-%S')
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
          prowler aws -M json-asff --no-color > "prowler-report-$TIMESTAMP.json" || true
  
      - name: Upload Prowler Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: prowler-report
          path: "prowler-report-*.json"

      - name: Upload JSON Report to S3
        run: |
          aws s3 cp "prowler-report-${{ env.TIMESTAMP }}.json" s3://prowler-reprort-cs-0001/deploy-report/prowler-report-${{ env.TIMESTAMP }}.json
  