name: Terraform Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ap-northeast-2
          
      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -out=tfplan > plan_output.txt
          if grep -q "No changes. Infrastructure is up-to-date." plan_output.txt; then
            echo "No changes detected. Skipping deployment."
            exit 0
          fi

      - name: Terraform Apply
        if: steps.plan.outcome == 'success'
        run: terraform apply -auto-approve tfplan

      # Terraform destroy 실행 (배포 성공 여부와 상관없이 항상 실행)
      - name: Cleanup on Failure
        if: failure()
        run: terraform destroy -auto-approve

          
          